// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateReport(arg1) {
  return window['go']['main']['App']['CreateReport'](arg1);
}

export function GetCurrentMatchList() {
  return window['go']['main']['App']['GetCurrentMatchList']();
}

export function GetCurrentSummoner() {
  return window['go']['main']['App']['GetCurrentSummoner']();
}

export function GetMatchInfo(arg1) {
  return window['go']['main']['App']['GetMatchInfo'](arg1);
}

export function GetMouseClick() {
  return window['go']['main']['App']['GetMouseClick']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function GreetAsyncViaEvent() {
  return window['go']['main']['App']['GreetAsyncViaEvent']();
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
