// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetMouseClick() {
  return window['go']['main']['App']['GetMouseClick']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function GreetAsyncViaEvent() {
  return window['go']['main']['App']['GreetAsyncViaEvent']();
}
