// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {lcu} from '../models';

export function GetCurrentMatchList():Promise<lcu.MatchList>;

export function GetCurrentSummoner():Promise<lcu.Summoner>;

export function GetMatchInfo(arg1:string):Promise<lcu.MatchInfo>;

export function GetMouseClick():Promise<number>;

export function Greet(arg1:string):Promise<string>;

export function GreetAsyncViaEvent():Promise<void>;

export function OpenFileDialog():Promise<Error>;
